site_url: https://statyba.netlify.app/
logo_url: https://statyba.netlify.app/image.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'pagrindinis'
    name: 'pagrindinis'
    files:
      - label: 'Pagrindinio puslapio informacija'
        name: 'info'
        file: 'assets/content/pagrindinis/pagrindinis.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Puslapio antraštė, name: title, widget: string, hint: 'Pagrindinio puslapio pavadinimas' }
          - { label: Mygtuko pavadinimas, name: buttonName, widget: string, hint: 'Mygtuko pavadinimas' }
          - { label: Telefono numeris, name: phone, widget: string, hint: 'Telefono numeris' }
          - { label: Elektroninis paštas, name: email, widget: string, hint: 'Elektroninis paštas' }
          - { label: Darbo laikas, name: workTime, widget: string, hint: 'Darbo laikas' }
          - { label: Adresas, name: address, widget: string, hint: 'Įmonės adresas' }
          - { label: Įmonės numeris, name: companyNumber, widget: string, hint: 'Įmonės registruotas numeris' }
          - { label: PVM kodas, name: pvm, widget: string, hint: 'PVM mokėtojo kodas' }
          - { label: metai, name: year, widget: string, hint: 'Autorių teisių metai (kiekvienais metais pakeiskite)' }
  - label: 'apie-mus'
    name: 'apie-mus'
    files:
      - label: 'Apie mus puslapio informacija'
        name: 'info'
        file: 'assets/content/apie-mus/apie-mus.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Puslapio antraštė, name: title, widget: string, hint: 'Pagrindinio puslapio pavadinimas' }
          - {
              label: Puslapio tekstas,
              name: description,
              widget: markdown,
              hint: 'Apie mus tekstas',
            }
          - { label: Mygtuko pavadinimas, name: buttonName, widget: string, hint: 'Mygtuko pavadinimas' }
          - { label: Metų patirtis, name: year, widget: string, hint: 'Metų patirtis' }
          - { label: Siūlymai, name: suggestions, widget: list, hint: 'Ką siųlote' }
  - name: 'atsiliepimai'
    label: 'atsiliepimai'
    label_singular: 'Project'
    folder: 'assets/content/atsiliepimai'
    create: true
    format: 'json'
    slug: '{{project_type}}-{{slug}}'
    preview_path: 'atsiliepimai/{{slug}}'
    fields:
      - {
          label: 'Project Type',
          name: 'project_type',
          widget: 'select',
          default: 'story',
          options: [{ label: 'Story', value: 'story' }, { label: 'Photo', value: 'photo' }],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'projektai'
    # identifier_field: name
    label: 'projektai'
    label_singular: 'Project'
    folder: 'assets/content/projektai'
    create: true
    format: 'json'
    slug: '{{project_type}}-{{slug}}'
    preview_path: 'projektai/{{slug}}'
    fields:
      - {
          label: 'Project Type',
          name: 'project_type',
          widget: 'select',
          default: 'story',
          options: [{ label: 'Story', value: 'story' }, { label: 'Photo', value: 'photo' }],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  # - name: 'story_projects'
  #   # identifier_field: name
  #   label: 'Story Projects'
  #   label_singular: 'Story Project'
  #   folder: 'assets/content/stories'
  #   create: true
  #   format: 'json'
  #   slug: '{{slug}}'
  #   preview_path: 'stories/{{slug}}'
  #   # filter: { field: 'project_type', value: 'story' }
  #   fields:
  #     # - { label: 'Project Type', name: 'project_type', widget: 'select', options: ['story', 'photo'] }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
  # - name: 'photo_projects'
  #   # identifier_field: name
  #   label: 'Photo Projects'
  #   label_singular: 'Photo Project'
  #   folder: 'assets/content/photos'
  #   create: true
  #   format: 'json'
  #   slug: '{{slug}}'
  #   preview_path: 'photos/{{slug}}'
  #   # filter: { field: 'project_type', value: 'photo' }
  #   fields:
  #     # - { label: 'Project Type', name: 'project_type', widget: 'select', options: ['story', 'photo'] }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
